MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_lrs
  BASE_LR: 0.00001
  GAMMA: 1.0
  MAX_ITER: 20000
  STEPS: [0, 11000]
  LRS: [0.00001, 0.000004]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v0upshare
  RESOLUTION: 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default: GaussianFill
TRAIN:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('CBIS_DDSM_train',)
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  SNAPSHOT_ITERS: 250
  USE_FLIPPED: True
  USE_V_FLIPPED: True
  ROTATION_ANGLES: (-20, 20)
  SHEAR_INT: (-0.2, 0.2)
  ZOOM: (0.8, 1.2)
  CHANNEL_SHIFT: (-0.1, 0.1)
TEST:
  FORCE_JSON_DATASET_EVAL: True
#  DATASETS: ('CBIS_DDSM','INbreast')
  DATASETS: ('CBIS_DDSM_val',)
  DETECTIONS_PER_IM: -1
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  SCORE_THRESH: 0.0
OUTPUT_DIR: /mnt/genesis/vegas/Detectron_Output/e2e_mask_R-50-C4
DOWNLOAD_CACHE: /mnt/genesis/vegas/Detectron-Cache
