MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_lrs
  BASE_LR: 0.00001
  GAMMA: 1.0
  MAX_ITER: 100000
  STEPS: [0, 50000]
  LRS: [0.00001, 0.00001]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: /mnt/genesis/vegas/CBIS_best_models/Faster-X101-32/model_iter137999.pkl
  DATASETS: ('INbreast_train',)
  SCALES: (500, 600, 700, 800, 900, )
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 1000
  USE_FLIPPED: True
  USE_V_FLIPPED: True
  ROTATION_ANGLES: (-20, 20)
  SHEAR_INT: (-0.2, 0.2)
TEST:
  FORCE_JSON_DATASET_EVAL: True
  DATASETS: ('INbreast_test',)
  DETECTIONS_PER_IM: -1
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  SCORE_THRESH: 0.0
OUTPUT_DIR: /mnt/genesis/vegas/Detectron_Output/e2e_faster_X-101-32x8d-FPN
DOWNLOAD_CACHE: /mnt/genesis/vegas/Detectron-Cache
