MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet101_conv4_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_lrs
  BASE_LR: 0.00001
  GAMMA: 1.0
  MAX_ITER: 100000
  STEPS: [0, 50000]
  LRS: [0.00001, 0.00001]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  WEIGHTS: /mnt/genesis/vegas/CBIS_best_models/Faster-R101-C4/model_iter116999.pkl
  DATASETS: ('INbreast_train',)
  SCALES: (500, 600, 700, 800, 900, )
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  SNAPSHOT_ITERS: 1000
  USE_FLIPPED: True
  USE_V_FLIPPED: True
  ROTATION_ANGLES: (-20, 20)
  SHEAR_INT: (-0.2, 0.2)
  CHANNEL_SHIFT: (-0.1, 0.1)
TEST:
  FORCE_JSON_DATASET_EVAL: True
  DATASETS: ('INbreast_test',)
  DETECTIONS_PER_IM: -1
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  SCORE_THRESH: 0.0
OUTPUT_DIR: /mnt/genesis/vegas/Detectron_Output/e2e_faster_R-101-C4_1
DOWNLOAD_CACHE: /mnt/genesis/vegas/Detectron-Cache
