MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_lrs
  BASE_LR: 0.00001
  GAMMA: 1.0
  MAX_ITER: 200000
  STEPS: [0, 100000]
  LRS: [0.0001, 0.00001]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
  INFERENCE_TH: 0.0
#  PRE_NMS_TOP_N: 1000
#  POSITIVE_OVERLAP: 0.6
#  NEGATIVE_OVERLAP: 0.5
TRAIN:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
  DATASETS: ('CBIS_DDSM_train',)
  SCALES: (800,)
  MAX_SIZE: 1333
  RPN_STRADDLE_THRESH: -1  # default 0
  IMS_PER_BATCH: 1
  SNAPSHOT_ITERS: 1000
#  USE_FLIPPED: True
#  USE_V_FLIPPED: True
#  ROTATION_ANGLES: (-20, 20)
#  SHEAR_INT: (-0.2, 0.2)
#  CHANNEL_SHIFT: (-0.1, 0.1)
TEST:
  FORCE_JSON_DATASET_EVAL: True
#  DATASETS: ('INbreast')
  DATASETS: ('CBIS_DDSM_test',)
  DETECTIONS_PER_IM: -1
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
  SCORE_THRESH: 0.0 # Not used on RetinaNet
#  IOU: 0.5
#  RPN_NMS_THRESH: 0.8
OUTPUT_DIR: /mnt/genesis/vegas/Detectron_Output/e2e_retinanet_R-101-FPN_no-augm
DOWNLOAD_CACHE: /mnt/genesis/vegas/Detectron-Cache
