MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_lrs
  BASE_LR: 0.00001
  GAMMA: 1.0
  MAX_ITER: 20000
  STEPS: [0, 11000]
  LRS: [0.00001, 0.000004]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v0upshare
  RESOLUTION: 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default: GaussianFill
TRAIN:
  #WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('CBIS_DDSMtrain',)
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  SNAPSHOT_ITERS: 250
TEST:
  FORCE_JSON_DATASET_EVAL: True
  DATASETS: ('INbreast',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  SCORE_THRESH: 0.0
OUTPUT_DIR: /media/gru/426be4ea-8d97-4683-bbb0-15978fea1da4/vegas/Detectron-output/scratch_e2e_mask_R-101-C4
DOWNLOAD_CACHE: /media/gru/426be4ea-8d97-4683-bbb0-15978fea1da4/vegas/Cache
