MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_lrs
  BASE_LR: 0.00001
  GAMMA: 1.0
  MAX_ITER: 20000
  STEPS: [0, 11000]
  LRS: [0.00001, 0.000004]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  #WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('CBIS_DDSMtrain',)
  SCALES: (800,)
  MAX_SIZE: 1333
  RPN_STRADDLE_THRESH: -1  # default 0
  SNAPSHOT_ITERS: 250
TEST:
  FORCE_JSON_DATASET_EVAL: True
  DATASETS: ('INbreast',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
  SCORE_THRESH: 0.0
OUTPUT_DIR: /media/gru/426be4ea-8d97-4683-bbb0-15978fea1da4/vegas/Detectron-output/scratch_retinanet_R-50-FPN
DOWNLOAD_CACHE: /media/gru/426be4ea-8d97-4683-bbb0-15978fea1da4/vegas/Cache
